#!/bin/bash

# Arguments:
#  PKGNAMES (optional): List of full packagenames to remove from the cache, if they exist.

# By default, if no PKGNAMES are given, clears the entire package cache

# source the config file
# if PKGNAMES specified:
#    foreach PKGNAME:
#       if exists in cache, remove file
# else:
#    remove entire cache, if it exists.

