.TH INSTALLKERNELPKG 8 "2021-05-18" "pkgtools-extras 1.0.0"
.SH NAME
installkernelpkg \- Install or upgrade packages, allowing multiple versions to remain installed.
.SH SYNOPSIS
.B installkernelpkg
[\fB\-d\fR, \fB\-\-dry\-run\fR]
[\fB\-s\fR, \fB\-\-skip\-missing\fR]
[\fB\-i\fR, \fB\-\-install\-new\fR]
[\fB\-r\fR, \fB\-\-reinstall\fR]
.IR PACKAGES ...
.SH DESCRIPTION
.B installkernelpkg
uses
.BR installpkg (8)
and
.BR removepkg (8)
to install and upgrade packages in a manner similar to
.BR upgradepkg (8),
but allowing multiple versions of the same package to be installed, side-by-side, often used for kernel packages.
.PP
.IR PACKAGES ...
should be a list of package filenames to install or upgrade.
.SH OPTIONS
.TP
.BR \-d ", " \-\-dry\-run
Does not actually modify the system.
Just reports what actions would be taken.
.TP
.BR \-s ", " \-\-skip\-missing
By default, if a specified package is not a readable file, the installation process halts, and does not install subsequent packages.
Specifying \fB\-\-skip\-missing\fR allows those missing packages to just be skipped, and later packages will be installed.
Note that other failures during the install process of a given package will not be ignored, and the process will halt.
.TP
.BR \-r ", " \-\-reinstall
By default, if the exact same package (name, version, architecture, build id) is already installed, it will not be re-installed.
Specifying \fB\-\-reinstall\fR will cause these packages to be re-installed.
This matches the behavior of
.BR upgradepkg (8)'s
\fB\-\-reinstall\fR option.
.TP
.BR \-i ", " \-\-install\-new
By default, if no version of the package (name and architecture must match) is already installed, the package will not be installed.
If \fB\-\-install\-new\fR is specified, these new packages will be installed.
This matches the behavior of
.BR upgradepkg (8)'s
\fB\-\-install\-new\fR option.
.SH EXIT STATUS
The exit status is \fB0\fR if all packages were installed or upgraded successfully.
Other possible exit statuses are:
.TP
.B 66
Missing or unreadable package file specified.
.TP
.B *
Other exit statuses may be returned by
.BR installpkg (8)
or
.BR removepkg (8)
if one of those programs fails.
.SH FILES
.TP
.I var/lib/pkgtools/packages/
Location of installed package meta-data files.
Used to determine status of a given package, and how it should be handled.
.SH BUGS
There is no locking of the package meta-data files in \fI/var/lib/pkgtools/packages\fR.
As a result, multiple instances of this program, or
.BR installpkg (8),
.BR upgradepkg (8),
or
.BR removepkg (8)
could interfere with each other.
.SH EXAMPLES
To install a new kernel version (along with associated modules), without removing the existing kernel packages:
.PP
.nf
.RS 5
.B installkernelpkg kernel\-generic\-5.10.30\-x86_64\-1 kernel\-modules\-5.10.30\-x86_64\-1
.RE
.fi
.SH AUTHORS
.R Jonathan L. Kaus <jlkaus@gmail.com>
.SH SEE ALSO
.BR installpkg (8),
.BR removepkg (8),
.BR upgradepkg (8).
